version: '3.9'

services:
  database:
    image: postgres:latest
    hostname: routes-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: routes
      POSTGRES_PASSWORD: routes123
      POSTGRES_DB: routesdb
  mensageria:
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"