spring:
  application:
    name: routes-microservice
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/routesdb}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: true
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    password: guest
    username: guest
    port: 5672
server:
  port: ${SERVER_PORT:8081}
logging:
  level:
    sql: info
    web: info
    root: info
management:
  endpoints:
    web:
      exposure:
        include: "*"

rabbit:
  listener:
    queue: ${LISTENER_QUEUE:routes.listener.queue}

routes:
  keys:
    google-maps: ${MAPS_KEY}