spring:
  application:
    name: routes-microservice
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/routesdb}
    username: ${DATABASE_USER:routes}
    password: ${DATABASE_PASSWORD:routes123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT:8081}
logging:
  level:
    sql: debug
    web: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"

routes:
  keys:
    google-maps: "API_KEY_AQUI"